name: Java CI

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure stage service
        run: |
            ls
            cat src/main/resources/config.properties
            sed -i "s~__AUTHPARAMS__~$AUTHPARAMS~" src/main/resources/config.properties
            sed -i "s~__DBURL__~$DBURL~" src/main/resources/config.properties
            sed -i "s~__DBUSERNAME__~$DBUSERNAME~" src/main/resources/config.properties
            sed -i "s~__DBPASSWORD__~$DBPASSWORD~" src/main/resources/config.properties
            cat src/main/resources/config.properties
        env:
            AUTHPARAMS: ${{ secrets.AUTHPARAMS }}
            DBURL: ${{ secrets.DBURL}}
            DBUSERNAME: ${{ secrets.DBUSERNAME }}
            DBPASSWORD: ${{ secrets.DBPASSWORD }}
      - uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.3.61
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn package
        #run: mvn kotlin:compile
      - name: Configure SSH
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/staging.key
            chmod 600 ~/.ssh/staging.key
            cat >>~/.ssh/config <<END
            Host staging
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
            END
        env:
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_KEY: ${{ secrets.PRIVATE_KEY}}
            SSH_HOST: ${{ secrets.HOST }}
      - name: SSH rm old version
        run: ssh staging 'rm ~/cryptomodule-1.1.0.jar'
      - name: SSH copy
        run: scp target/cryptomodule-1.1.0.jar staging:~/cryptomodule-1.1.0.jar
      - name: Upload math result
        uses: actions/upload-artifact@v2
        with:
          name: module
          path: target/cryptomodule-1.1.0.jar
  restart:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: Configure SSH
          run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/staging.key
            chmod 600 ~/.ssh/staging.key
            cat >>~/.ssh/config <<END
            Host staging
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
            END
          env:
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_KEY: ${{ secrets.PRIVATE_KEY}}
            SSH_HOST: ${{ secrets.HOST }}
        - name: SSH restart service 
          run: ssh staging 'sudo systemctl restart crypto'
        - name: SSH status service 
          run: ssh staging 'sudo systemctl status crypto'
