name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn package
      - name: ls
        run: ls target
      - name: Upload math result
        uses: actions/upload-artifact@v2
        with:
          name: module
          path: target/cryptomodule-1.1.0.jar
  copy:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: Configure SSH
          run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/staging.key
            chmod 600 ~/.ssh/staging.key
            cat >>~/.ssh/config <<END
            Host staging
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
            END
          env:
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_KEY: ${{ secrets.PRIVATE_KEY}}
            SSH_HOST: ${{ secrets.HOST }}
        - name: SSH copy
          run: scp target/cryptomodule-1.1.0.jar staging:~/liv/cryptomodule-1.1.0.jar
        - name: SSH test
          run: ssh staging 'ls liv'
        - name: copy file via ssh password
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.PRIVATE_KEY}}
            port: 22
            source: "target/cryptomodule-1.1.0.jar"
            target: "liv/"
  push:
    needs: copy
    name: push
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
