name: Run manual restart

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: ''
      home:
        description: 'are you sure '
        required: false
        default: ''

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
        - name: Configure SSH
          run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/staging.key
            chmod 600 ~/.ssh/staging.key
            cat >>~/.ssh/config <<END
            Host staging
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
            END
          env:
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_KEY: ${{ secrets.PRIVATE_KEY}}
            SSH_HOST: ${{ secrets.HOST }}
        - name: SSH restart service 
          run: ssh staging 'sudo systemctl restart crypto'
        - name: SSH status service 
          run: ssh staging 'sudo systemctl status crypto'
